openapi: 3.1.0
info:
  version: 1.0.0
  title: Contact book
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Contact book's app

tags:
  - name: Contacts
    description: Operations with contacts

servers:
  - url: 'http://localhost:3000'
  - url: 'https://contacts-app-vvuh.onrender.com/'

paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/auth/register/post.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/auth/logout/post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/auth/refresh/post.yaml'
  /auth/sendResetEmail:
    post:
      $ref: '../swagger/paths/auth/sendResetEmail/post.yaml'
  /auth/resetPassword:
    post:
      $ref: '../swagger/paths/auth/resetPassword/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer